CWE226_Sensitive_Information_Uncleared_Before_Release__w32_char_alloca_01: CWE226_Sensitive_Information_Uncleared_Before_Release__w32_char_alloca_01.c
	gcc -lcrypt -o CWE226_Sensitive_Information_Uncleared_Before_Release__w32_char_alloca_01 CWE226_Sensitive_Information_Uncleared_Before_Release__w32_char_alloca_01.c

